Django_Blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('user_records.urls')),
]

Django_Blog/user_records/urls.py
from django.urls import path

from . import views

app_name = 'user_records'
urlpatterns = [
    # Головна сторінка
    path('', views.index, name='index'),
    # Сторінка що відображає всі теми
    path('topics/', views.topics, name='topics'),
    # Сторінка призначена окремій темі
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Сторінка для додавання нової теми
    path('new_topic/', views.new_topic, name='new_topic'),
    # Сторінка для додавання нового допису
    path('new_entry/<int:topic_id>/',views.new_entry, name='new_entry'),
    # Сторінка для редагування допису
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

Django_Blog/users/urls.py
from django.urls import path, include

from users import views

app_name = 'users'

urlpatterns = [
    # Додати уставні URL для автентифікації
    path('', include('django.contrib.auth.urls')),
    # Сторінка реєстрації.
    path('register/', views.register, name='register'),
]

Django_Blog/user_records/models.py
from django.db import models
from django.contrib.auth.models import User
class Topic(models.Model):
    text = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) < 50:
            return self.text
        else:
            return f"{self.text[:50]}..."

Django_Blog/users/models.py
from django.db import models

# Create your models here.

Django_Blog/user_records/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text' : ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text' : ''}
        widgets = {'text' : forms.Textarea(attrs={'cols' : 80})}

Django_Blog/user_records/views.py
from django.shortcuts import render, redirect

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

def index(request):
    return render(request, 'user_records/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics' : topics}
    return render(request, 'user_records/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'user_records/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # Жодних даних не відправлено; створити порожню форму
        form = TopicForm()
    else:
        # відправляємо POST; обробити дані.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('user_records:topics')

    # Показати порожню або не дійсну форму
    context = {'form' : form}
    return render(request, 'user_records/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('user_records:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'user_records/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)

    if request.method != 'POST':
        form = EntryForm(instance=entry)

    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('user_records:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'user_records/edit_entry.html', context)


def check_topic_owner(request, topic):
    if topic.owner != request.user:
        raise Http404

Django_Blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != 'POST':
        # Показати порожню форму реєстрації
        form = UserCreationForm()
    else:
        # Опрацювати заповнену форму
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Авторизація та скерування на головну сторінку
            login(request, new_user)
            return redirect('user_records:index')
    # Показати порожню форму
    context = {'form': form}
    return render(request, 'registration/register.html', context)

Django_Blog/user_records/templates/user_records/base.html
<p>
    <a href="{% url 'user_records:index' %}">Learning Log - </a>
    <a href="{% url 'user_records:topics'%}">Topics</a> -
    {% if user.is_authenticated %}
        Hello, {{ user.username }}
       <form action="{% url 'users:logout' %}" method="post">
   {% csrf_token %}
    <button type="submit" class="btn btn-success">log out</button>
</form>
    {% else %}
    <a href="{% url 'users:register' %}">Register</a> -
    <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}
{% endblock content %}

Django_Blog/user_records/templates/user_records/edit_entry.html
{% extends "user_records/base.html" %}

{% block content %}

<p><a href="{% url 'user_records:topic' topic.id %}">{{ topic }}</a> </p>

<p>Edit entry:</p>

<form action="{% url 'user_records:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

Django_Blog/user_records/templates/user_records/index.html
{% extends "user_records/base.html" %}

{% block content %}
<p>Blog</p>
<p>
    This Blog help you keep track of your life.
</p>
{% endblock content %}

Django_Blog/user_records/templates/user_records/new_entry.html
{% extends "user_records/base.html" %}

{% block content %}

<p><a href="{% url 'user_records:topic' topic.id %}"> {{ topic }}</a> </p>
<p> Add a new entry: </p>
<form action="{% url 'user_records:new_entry' topic.id %}" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add entry</button>
</form>

{% endblock content %}

Django_Blog/user_records/templates/user_records/new_topic.html
{% extends "user_records/base.html" %}

{% block content %}
<p>Add a new topic:</p>
<form action="{% url 'user_records:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add topic</button>
</form>

{% endblock content %}

Django_Blog/user_records/templates/user_records/topic.html
{% extends 'user_records/base.html' %}

{% block content %}

<p>Topic: {{ topic }}</p>

<p>Entries:</p>
<p>
    <a href="{% url 'user_records:new_entry' topic.id %}"> Add new entry</a>
</p>
<ul>
    {% for entry in entries %}
	    <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <a href="{% url 'user_records:edit_entry' entry.id %}">Edit entry</a>
            </p>
        </li>

    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'user_records:new_topic' %}">Add a new topic</a>

{% endblock content %}

Django_Blog/user_records/templates/user_records/topics.html
{% extends "user_records/base.html" %}

{% block content %}

<p>Topics</p>
<a href="{% url 'user_records:new_topic' %}">Add a new topic</a>
<ul>
    {% for topic in topics %}
	    <li>
            <a href="{% url 'user_records:topic' topic.id %}">{{ topic }}</a>
        </li>

    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}